# Generated by Django 5.0.6 on 2024-07-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
